# Build stage
FROM gradle:8.6.0-jdk21-alpine AS build
WORKDIR /app
COPY build.gradle.kts .
COPY src ./src
RUN gradle bootJar --no-daemon

# Run stage
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/build/libs/*.jar app.jar
EXPOSE 8082
ENTRYPOINT ["java", "-jar", "app.jar"]
